language: c
env:
  - PPA=avsm/ocaml40+opam10
  - PPA=avsm/ocaml40+opam11
  - PPA=avsm/ocaml41+opam10
  - PPA=avsm/ocaml41+opam11

before_install: ./travis.sh before_install
install: ./travis.sh install
script: ./travis.sh script
git:
    submodules: false